version: '3.8'

services:
  api-esg-fiap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-esg-fiap
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - esg-network

networks:
  esg-network:
    driver: bridge